version: '2'
services:
  web:
    build: ./web
    ports:
      - "3003:3003"
      - "443:443"
    depends_on:
      - app
    restart: always
    volumes_from:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    depends_on:
      - db
    restart: always
    volumes:
      - ./app/wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./app/wordpress:/var/www/html

  db:
    image: mysql:5.7.19
    env_file: .env
    ports:
      - "3307:3307"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql

volumes:
  db-data: